// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: go/api/buildeventstream/buildeventstream.proto

package buildeventstream

import (
	command "github.com/bazelbuild/remote-apis-sdks/go/api/command"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionStarted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsolePrintout string                 `protobuf:"bytes,1,opt,name=console_printout,json=consolePrintout,proto3" json:"console_printout,omitempty"` // Regular UTF-8 output; normal text (this is the action execution printout).
	PrimaryOutput   string                 `protobuf:"bytes,2,opt,name=primary_output,json=primaryOutput,proto3" json:"primary_output,omitempty"`       // The file name of the primary output, which identifies the action uniquely.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionStarted) Reset() {
	*x = ActionStarted{}
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStarted) ProtoMessage() {}

func (x *ActionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStarted.ProtoReflect.Descriptor instead.
func (*ActionStarted) Descriptor() ([]byte, []int) {
	return file_go_api_buildeventstream_buildeventstream_proto_rawDescGZIP(), []int{0}
}

func (x *ActionStarted) GetConsolePrintout() string {
	if x != nil {
		return x.ConsolePrintout
	}
	return ""
}

func (x *ActionStarted) GetPrimaryOutput() string {
	if x != nil {
		return x.PrimaryOutput
	}
	return ""
}

type ActionCompleted struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ActionDigest string                 `protobuf:"bytes,1,opt,name=action_digest,json=actionDigest,proto3" json:"action_digest,omitempty"` // The action digest in canonical format <hash>/<size>.
	Result       *command.CommandResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	StdoutDigest string                 `protobuf:"bytes,3,opt,name=stdout_digest,json=stdoutDigest,proto3" json:"stdout_digest,omitempty"` // In canonical format <hash>/<size>.
	StderrDigest string                 `protobuf:"bytes,4,opt,name=stderr_digest,json=stderrDigest,proto3" json:"stderr_digest,omitempty"` // In canonical format <hash>/<size>.
	// It is currently difficult to rely on the stdout/err being available remotely, so we need to pass the whole thing.
	Stdout            string            `protobuf:"bytes,7,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr            string            `protobuf:"bytes,8,opt,name=stderr,proto3" json:"stderr,omitempty"`
	PrimaryOutput     string            `protobuf:"bytes,5,opt,name=primary_output,json=primaryOutput,proto3" json:"primary_output,omitempty"` // The file name of the primary output, which identifies the action uniquely.
	OutputFileDigests map[string]string `protobuf:"bytes,6,rep,name=output_file_digests,json=outputFileDigests,proto3" json:"output_file_digests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActionCompleted) Reset() {
	*x = ActionCompleted{}
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCompleted) ProtoMessage() {}

func (x *ActionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCompleted.ProtoReflect.Descriptor instead.
func (*ActionCompleted) Descriptor() ([]byte, []int) {
	return file_go_api_buildeventstream_buildeventstream_proto_rawDescGZIP(), []int{1}
}

func (x *ActionCompleted) GetActionDigest() string {
	if x != nil {
		return x.ActionDigest
	}
	return ""
}

func (x *ActionCompleted) GetResult() *command.CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActionCompleted) GetStdoutDigest() string {
	if x != nil {
		return x.StdoutDigest
	}
	return ""
}

func (x *ActionCompleted) GetStderrDigest() string {
	if x != nil {
		return x.StderrDigest
	}
	return ""
}

func (x *ActionCompleted) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ActionCompleted) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ActionCompleted) GetPrimaryOutput() string {
	if x != nil {
		return x.PrimaryOutput
	}
	return ""
}

func (x *ActionCompleted) GetOutputFileDigests() map[string]string {
	if x != nil {
		return x.OutputFileDigests
	}
	return nil
}

type BuildLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          map[string]string      `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Name -> canonical digest. Maybe will be replaced by the Stats.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildLogs) Reset() {
	*x = BuildLogs{}
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogs) ProtoMessage() {}

func (x *BuildLogs) ProtoReflect() protoreflect.Message {
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogs.ProtoReflect.Descriptor instead.
func (*BuildLogs) Descriptor() ([]byte, []int) {
	return file_go_api_buildeventstream_buildeventstream_proto_rawDescGZIP(), []int{2}
}

func (x *BuildLogs) GetLogs() map[string]string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type BuildMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildMetrics) Reset() {
	*x = BuildMetrics{}
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildMetrics) ProtoMessage() {}

func (x *BuildMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildMetrics.ProtoReflect.Descriptor instead.
func (*BuildMetrics) Descriptor() ([]byte, []int) {
	return file_go_api_buildeventstream_buildeventstream_proto_rawDescGZIP(), []int{3}
}

// Message describing a build event. More details, which are specific to the kind of event
// that is observed, is provided in the payload. More options for the payload
// might be added in the future.
// This protocol is for RE plugins only -- meaning, the build tool is not aware of the build graph, only
// of individual actions.
type BuildEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BuildEvent_ActionStarted
	//	*BuildEvent_ActionCompleted
	//	*BuildEvent_BuildLogs
	//	*BuildEvent_BuildMetrics
	Payload       isBuildEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent) Reset() {
	*x = BuildEvent{}
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent) ProtoMessage() {}

func (x *BuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_go_api_buildeventstream_buildeventstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent.ProtoReflect.Descriptor instead.
func (*BuildEvent) Descriptor() ([]byte, []int) {
	return file_go_api_buildeventstream_buildeventstream_proto_rawDescGZIP(), []int{4}
}

func (x *BuildEvent) GetPayload() isBuildEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BuildEvent) GetActionStarted() *ActionStarted {
	if x != nil {
		if x, ok := x.Payload.(*BuildEvent_ActionStarted); ok {
			return x.ActionStarted
		}
	}
	return nil
}

func (x *BuildEvent) GetActionCompleted() *ActionCompleted {
	if x != nil {
		if x, ok := x.Payload.(*BuildEvent_ActionCompleted); ok {
			return x.ActionCompleted
		}
	}
	return nil
}

func (x *BuildEvent) GetBuildLogs() *BuildLogs {
	if x != nil {
		if x, ok := x.Payload.(*BuildEvent_BuildLogs); ok {
			return x.BuildLogs
		}
	}
	return nil
}

func (x *BuildEvent) GetBuildMetrics() *BuildMetrics {
	if x != nil {
		if x, ok := x.Payload.(*BuildEvent_BuildMetrics); ok {
			return x.BuildMetrics
		}
	}
	return nil
}

type isBuildEvent_Payload interface {
	isBuildEvent_Payload()
}

type BuildEvent_ActionStarted struct {
	ActionStarted *ActionStarted `protobuf:"bytes,1,opt,name=action_started,json=actionStarted,proto3,oneof"`
}

type BuildEvent_ActionCompleted struct {
	ActionCompleted *ActionCompleted `protobuf:"bytes,2,opt,name=action_completed,json=actionCompleted,proto3,oneof"`
}

type BuildEvent_BuildLogs struct {
	BuildLogs *BuildLogs `protobuf:"bytes,3,opt,name=build_logs,json=buildLogs,proto3,oneof"`
}

type BuildEvent_BuildMetrics struct {
	BuildMetrics *BuildMetrics `protobuf:"bytes,4,opt,name=build_metrics,json=buildMetrics,proto3,oneof"`
}

func (*BuildEvent_ActionStarted) isBuildEvent_Payload() {}

func (*BuildEvent_ActionCompleted) isBuildEvent_Payload() {}

func (*BuildEvent_BuildLogs) isBuildEvent_Payload() {}

func (*BuildEvent_BuildMetrics) isBuildEvent_Payload() {}

var File_go_api_buildeventstream_buildeventstream_proto protoreflect.FileDescriptor

const file_go_api_buildeventstream_buildeventstream_proto_rawDesc = "" +
	"\n" +
	".go/api/buildeventstream/buildeventstream.proto\x12\x19build_event_stream_plugin\x1a\x1cgo/api/command/command.proto\"a\n" +
	"\rActionStarted\x12)\n" +
	"\x10console_printout\x18\x01 \x01(\tR\x0fconsolePrintout\x12%\n" +
	"\x0eprimary_output\x18\x02 \x01(\tR\rprimaryOutput\"\xbc\x03\n" +
	"\x0fActionCompleted\x12#\n" +
	"\raction_digest\x18\x01 \x01(\tR\factionDigest\x12*\n" +
	"\x06result\x18\x02 \x01(\v2\x12.cmd.CommandResultR\x06result\x12#\n" +
	"\rstdout_digest\x18\x03 \x01(\tR\fstdoutDigest\x12#\n" +
	"\rstderr_digest\x18\x04 \x01(\tR\fstderrDigest\x12\x16\n" +
	"\x06stdout\x18\a \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\b \x01(\tR\x06stderr\x12%\n" +
	"\x0eprimary_output\x18\x05 \x01(\tR\rprimaryOutput\x12q\n" +
	"\x13output_file_digests\x18\x06 \x03(\v2A.build_event_stream_plugin.ActionCompleted.OutputFileDigestsEntryR\x11outputFileDigests\x1aD\n" +
	"\x16OutputFileDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\tBuildLogs\x12B\n" +
	"\x04logs\x18\x01 \x03(\v2..build_event_stream_plugin.BuildLogs.LogsEntryR\x04logs\x1a7\n" +
	"\tLogsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fBuildMetrics\"\xda\x02\n" +
	"\n" +
	"BuildEvent\x12Q\n" +
	"\x0eaction_started\x18\x01 \x01(\v2(.build_event_stream_plugin.ActionStartedH\x00R\ractionStarted\x12W\n" +
	"\x10action_completed\x18\x02 \x01(\v2*.build_event_stream_plugin.ActionCompletedH\x00R\x0factionCompleted\x12E\n" +
	"\n" +
	"build_logs\x18\x03 \x01(\v2$.build_event_stream_plugin.BuildLogsH\x00R\tbuildLogs\x12N\n" +
	"\rbuild_metrics\x18\x04 \x01(\v2'.build_event_stream_plugin.BuildMetricsH\x00R\fbuildMetricsB\t\n" +
	"\apayloadB@Z>github.com/bazelbuild/remote-apis-sdks/go/api/buildeventstreamb\x06proto3"

var (
	file_go_api_buildeventstream_buildeventstream_proto_rawDescOnce sync.Once
	file_go_api_buildeventstream_buildeventstream_proto_rawDescData []byte
)

func file_go_api_buildeventstream_buildeventstream_proto_rawDescGZIP() []byte {
	file_go_api_buildeventstream_buildeventstream_proto_rawDescOnce.Do(func() {
		file_go_api_buildeventstream_buildeventstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_api_buildeventstream_buildeventstream_proto_rawDesc), len(file_go_api_buildeventstream_buildeventstream_proto_rawDesc)))
	})
	return file_go_api_buildeventstream_buildeventstream_proto_rawDescData
}

var file_go_api_buildeventstream_buildeventstream_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_go_api_buildeventstream_buildeventstream_proto_goTypes = []any{
	(*ActionStarted)(nil),         // 0: build_event_stream_plugin.ActionStarted
	(*ActionCompleted)(nil),       // 1: build_event_stream_plugin.ActionCompleted
	(*BuildLogs)(nil),             // 2: build_event_stream_plugin.BuildLogs
	(*BuildMetrics)(nil),          // 3: build_event_stream_plugin.BuildMetrics
	(*BuildEvent)(nil),            // 4: build_event_stream_plugin.BuildEvent
	nil,                           // 5: build_event_stream_plugin.ActionCompleted.OutputFileDigestsEntry
	nil,                           // 6: build_event_stream_plugin.BuildLogs.LogsEntry
	(*command.CommandResult)(nil), // 7: cmd.CommandResult
}
var file_go_api_buildeventstream_buildeventstream_proto_depIdxs = []int32{
	7, // 0: build_event_stream_plugin.ActionCompleted.result:type_name -> cmd.CommandResult
	5, // 1: build_event_stream_plugin.ActionCompleted.output_file_digests:type_name -> build_event_stream_plugin.ActionCompleted.OutputFileDigestsEntry
	6, // 2: build_event_stream_plugin.BuildLogs.logs:type_name -> build_event_stream_plugin.BuildLogs.LogsEntry
	0, // 3: build_event_stream_plugin.BuildEvent.action_started:type_name -> build_event_stream_plugin.ActionStarted
	1, // 4: build_event_stream_plugin.BuildEvent.action_completed:type_name -> build_event_stream_plugin.ActionCompleted
	2, // 5: build_event_stream_plugin.BuildEvent.build_logs:type_name -> build_event_stream_plugin.BuildLogs
	3, // 6: build_event_stream_plugin.BuildEvent.build_metrics:type_name -> build_event_stream_plugin.BuildMetrics
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_go_api_buildeventstream_buildeventstream_proto_init() }
func file_go_api_buildeventstream_buildeventstream_proto_init() {
	if File_go_api_buildeventstream_buildeventstream_proto != nil {
		return
	}
	file_go_api_buildeventstream_buildeventstream_proto_msgTypes[4].OneofWrappers = []any{
		(*BuildEvent_ActionStarted)(nil),
		(*BuildEvent_ActionCompleted)(nil),
		(*BuildEvent_BuildLogs)(nil),
		(*BuildEvent_BuildMetrics)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_api_buildeventstream_buildeventstream_proto_rawDesc), len(file_go_api_buildeventstream_buildeventstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_api_buildeventstream_buildeventstream_proto_goTypes,
		DependencyIndexes: file_go_api_buildeventstream_buildeventstream_proto_depIdxs,
		MessageInfos:      file_go_api_buildeventstream_buildeventstream_proto_msgTypes,
	}.Build()
	File_go_api_buildeventstream_buildeventstream_proto = out.File
	file_go_api_buildeventstream_buildeventstream_proto_goTypes = nil
	file_go_api_buildeventstream_buildeventstream_proto_depIdxs = nil
}
